from enum import Enum


class SemanticType(str, Enum):
    BUILDING_MASS = "BUILDING_MASS"
    FLOOR_VOLUME = "FLOOR_VOLUME"
    BASEMENT_VOLUME = "BASEMENT_VOLUME"
    UTILITY_CORRIDOR = "UTILITY_CORRIDOR"
    AIRSPACE_VOLUME = "AIRSPACE_VOLUME"
    OTHER_CANDIDATE = "OTHER_CANDIDATE"


class ConfidenceLevel(str, Enum):
    VERIFIED = "VERIFIED"
    STRONG = "STRONG"
    MODERATE = "MODERATE"
    WEAK = "WEAK"
    UNKNOWN = "UNKNOWN"


class IssueSeverity(str, Enum):
    INFO = "INFO"
    WARN = "WARN"
    ERROR = "ERROR"
    BLOCKER = "BLOCKER"


class UnitStatus(str, Enum):
    DRAFT = "DRAFT"
    GENERATED = "GENERATED"
    VALIDATED = "VALIDATED"
    UNDER_REVIEW = "UNDER_REVIEW"
    CORRECTED = "CORRECTED"
    REVALIDATED = "REVALIDATED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class EvidenceType(str, Enum):
    PARCEL_BOUNDARY = "PARCEL_BOUNDARY"
    BUILDING_FOOTPRINT = "BUILDING_FOOTPRINT"
    FLOOR_PLAN = "FLOOR_PLAN"
    LIDAR_POINTCLOUD = "LIDAR_POINTCLOUD"
    ORTHOIMAGERY = "ORTHOIMAGERY"
    DEM_DSM = "DEM_DSM"
    SURVEY_MEASUREMENT = "SURVEY_MEASUREMENT"


class ReviewDecisionType(str, Enum):
    ACCEPT = "ACCEPT"
    REQUEST_CORRECTION = "REQUEST_CORRECTION"
    REJECT = "REJECT"


class ApprovalStatus(str, Enum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class AuditAction(str, Enum):
    CANDIDATE_CREATED = "CANDIDATE_CREATED"
    VALIDATION_EXECUTED = "VALIDATION_EXECUTED"
    EVIDENCE_REGISTERED = "EVIDENCE_REGISTERED"
    EVIDENCE_VERIFIED = "EVIDENCE_VERIFIED"
    REVIEW_STARTED = "REVIEW_STARTED"
    REVIEW_SUBMITTED = "REVIEW_SUBMITTED"
    CORRECTION_REQUESTED = "CORRECTION_REQUESTED"
    CORRECTION_SUBMITTED = "CORRECTION_SUBMITTED"
    REVISION_CREATED = "REVISION_CREATED"
    REVALIDATION_EXECUTED = "REVALIDATION_EXECUTED"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_GRANTED = "APPROVAL_GRANTED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    CANDIDATE_REJECTED = "CANDIDATE_REJECTED"
    EXPORT_GENERATED = "EXPORT_GENERATED"


class GateType(str, Enum):
    GATE_A = "GATE_A"
    GATE_B = "GATE_B"
    GATE_C = "GATE_C"

