from enum import Enum


class SemanticType(str, Enum):
    BUILDING_MASS = "BUILDING_MASS"
    FLOOR_VOLUME = "FLOOR_VOLUME"
    BASEMENT_VOLUME = "BASEMENT_VOLUME"
    UTILITY_CORRIDOR = "UTILITY_CORRIDOR"
    AIRSPACE_VOLUME = "AIRSPACE_VOLUME"
    OTHER_CANDIDATE = "OTHER_CANDIDATE"


class ConfidenceLevel(str, Enum):
    VERIFIED = "VERIFIED"
    STRONG = "STRONG"
    MODERATE = "MODERATE"
    WEAK = "WEAK"
    UNKNOWN = "UNKNOWN"


class IssueSeverity(str, Enum):
    INFO = "INFO"
    WARN = "WARN"
    ERROR = "ERROR"
    BLOCKER = "BLOCKER"


class UnitStatus(str, Enum):
    DRAFT = "DRAFT"
    GENERATED = "GENERATED"
    VALIDATION_PENDING = "VALIDATION_PENDING"
    VALIDATED = "VALIDATED"
    ISSUES_FOUND = "ISSUES_FOUND"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class EvidenceType(str, Enum):
    PARCEL_BOUNDARY = "PARCEL_BOUNDARY"
    BUILDING_FOOTPRINT = "BUILDING_FOOTPRINT"
    FLOOR_PLAN = "FLOOR_PLAN"
    LIDAR_POINTCLOUD = "LIDAR_POINTCLOUD"
    ORTHOIMAGERY = "ORTHOIMAGERY"
    DEM_DSM = "DEM_DSM"
    SURVEY_MEASUREMENT = "SURVEY_MEASUREMENT"
