from enum import Enum


class SemanticType(str, Enum):
    BUILDING_MASS = "BUILDING_MASS"
    FLOOR_VOLUME = "FLOOR_VOLUME"
    BASEMENT_VOLUME = "BASEMENT_VOLUME"
    UTILITY_CORRIDOR = "UTILITY_CORRIDOR"
    AIRSPACE_VOLUME = "AIRSPACE_VOLUME"
    OTHER_CANDIDATE = "OTHER_CANDIDATE"


class ConfidenceLevel(str, Enum):
    VERIFIED = "VERIFIED"
    STRONG = "STRONG"
    MODERATE = "MODERATE"
    WEAK = "WEAK"
    UNKNOWN = "UNKNOWN"


class IssueSeverity(str, Enum):
    INFO = "INFO"
    WARN = "WARN"
    ERROR = "ERROR"
    BLOCKER = "BLOCKER"


class UnitStatus(str, Enum):
    DRAFT = "DRAFT"
    GENERATED = "GENERATED"
    VALIDATED = "VALIDATED"
    UNDER_REVIEW = "UNDER_REVIEW"
    CORRECTED = "CORRECTED"
    REVALIDATED = "REVALIDATED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class EvidenceType(str, Enum):
    PARCEL_BOUNDARY = "PARCEL_BOUNDARY"
    BUILDING_FOOTPRINT = "BUILDING_FOOTPRINT"
    FLOOR_PLAN = "FLOOR_PLAN"
    LIDAR_POINTCLOUD = "LIDAR_POINTCLOUD"
    ORTHOIMAGERY = "ORTHOIMAGERY"
    DEM_DSM = "DEM_DSM"
    SURVEY_MEASUREMENT = "SURVEY_MEASUREMENT"


class ReviewDecisionType(str, Enum):
    ACCEPT = "ACCEPT"
    REQUEST_CORRECTION = "REQUEST_CORRECTION"
    REJECT = "REJECT"


class ApprovalStatus(str, Enum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class AuditAction(str, Enum):
    CANDIDATE_CREATED = "CANDIDATE_CREATED"
    VALIDATION_EXECUTED = "VALIDATION_EXECUTED"
    EVIDENCE_REGISTERED = "EVIDENCE_REGISTERED"
    EVIDENCE_VERIFIED = "EVIDENCE_VERIFIED"
    REVIEW_STARTED = "REVIEW_STARTED"
    REVIEW_SUBMITTED = "REVIEW_SUBMITTED"
    CORRECTION_REQUESTED = "CORRECTION_REQUESTED"
    CORRECTION_SUBMITTED = "CORRECTION_SUBMITTED"
    REVISION_CREATED = "REVISION_CREATED"
    REVALIDATION_EXECUTED = "REVALIDATION_EXECUTED"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_GRANTED = "APPROVAL_GRANTED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    CANDIDATE_REJECTED = "CANDIDATE_REJECTED"
    EXPORT_GENERATED = "EXPORT_GENERATED"
    # AI Intelligence Audit Actions (Slice 3)
    AI_INFERENCE_STARTED = "AI_INFERENCE_STARTED"
    AI_INFERENCE_COMPLETED = "AI_INFERENCE_COMPLETED"
    AI_CANDIDATE_CREATED = "AI_CANDIDATE_CREATED"
    AI_CANDIDATE_REJECTED = "AI_CANDIDATE_REJECTED"
    AI_OUTPUT_VALIDATION_FAILED = "AI_OUTPUT_VALIDATION_FAILED"
    AI_ANOMALY_DETECTED = "AI_ANOMALY_DETECTED"
    AI_REVIEWED = "AI_REVIEWED"
    # Slice 4 Validation Intelligence & Reproducibility Audit Actions
    AI_VALIDATION_DISAGREEMENT = "AI_VALIDATION_DISAGREEMENT"
    REPRODUCIBILITY_SNAPSHOT_CREATED = "REPRODUCIBILITY_SNAPSHOT_CREATED"
    RULESET_EXECUTED = "RULESET_EXECUTED"
    HUMAN_OVERRIDE_RECORDED = "HUMAN_OVERRIDE_RECORDED"
    AI_FAILURE_LOGGED = "AI_FAILURE_LOGGED"
    MODEL_COMPARISON_EXECUTED = "MODEL_COMPARISON_EXECUTED"

    # Slice 5 Operational & Deployment Audit Actions
    SYSTEM_STARTED = "SYSTEM_STARTED"
    DATABASE_BOOTSTRAPPED = "DATABASE_BOOTSTRAPPED"
    MIGRATION_VERIFIED = "MIGRATION_VERIFIED"
    DATA_INTEGRITY_CHECKED = "DATA_INTEGRITY_CHECKED"
    EVIDENCE_INGESTED = "EVIDENCE_INGESTED"
    EVIDENCE_REJECTED = "EVIDENCE_REJECTED"
    EVIDENCE_DUPLICATE_DETECTED = "EVIDENCE_DUPLICATE_DETECTED"
    EVIDENCE_CONFLICT_DETECTED = "EVIDENCE_CONFLICT_DETECTED"
    EVIDENCE_MARKED_STALE = "EVIDENCE_MARKED_STALE"
    VALIDATION_MARKED_STALE = "VALIDATION_MARKED_STALE"
    IMPORT_COMPLETED = "IMPORT_COMPLETED"
    AI_FALLBACK_ACTIVATED = "AI_FALLBACK_ACTIVATED"
    FIELD_SIMULATION_STARTED = "FIELD_SIMULATION_STARTED"
    FIELD_SIMULATION_COMPLETED = "FIELD_SIMULATION_COMPLETED"


class GateType(str, Enum):
    GATE_A = "GATE_A"
    GATE_B = "GATE_B"
    GATE_C = "GATE_C"


class ObservationType(str, Enum):
    FLOOR_BOUNDARY = "FLOOR_BOUNDARY"
    BUILDING_FOOTPRINT = "BUILDING_FOOTPRINT"
    LEVEL_LABEL = "LEVEL_LABEL"
    ELEVATION_MARK = "ELEVATION_MARK"
    ROOM_BOUNDARY = "ROOM_BOUNDARY"
    STRUCTURAL_EDGE = "STRUCTURAL_EDGE"
    PARCEL_BOUNDARY = "PARCEL_BOUNDARY"


class CandidateStatus(str, Enum):
    AI_CANDIDATE = "AI_CANDIDATE"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    CORRECTED = "CORRECTED"


class AnomalyType(str, Enum):
    OVERLAPPING_LEVELS = "OVERLAPPING_LEVELS"
    VERTICAL_GAP = "VERTICAL_GAP"
    MISSING_LEVEL = "MISSING_LEVEL"
    INCONSISTENT_LABEL = "INCONSISTENT_LABEL"
    FOOTPRINT_MISMATCH = "FOOTPRINT_MISMATCH"
    EVIDENCE_CONFLICT = "EVIDENCE_CONFLICT"
    PARCEL_EXTENT_VIOLATION = "PARCEL_EXTENT_VIOLATION"
    SUSPICIOUS_GEOMETRY = "SUSPICIOUS_GEOMETRY"
    DUPLICATE_CANDIDATE = "DUPLICATE_CANDIDATE"


class ExtractionMethod(str, Enum):
    HEURISTIC_CAD_EXTRACTOR = "HEURISTIC_CAD_EXTRACTOR"
    AI_OCR_VECTORIZER = "AI_OCR_VECTORIZER"
    SYNTHETIC_INTERPRETATION = "SYNTHETIC_INTERPRETATION"
    STRUCTURED_METADATA_PARSER = "STRUCTURED_METADATA_PARSER"


class ReasonCode(str, Enum):
    FOOTPRINT_MATCH = "FOOTPRINT_MATCH"
    FLOOR_PLAN_MATCH = "FLOOR_PLAN_MATCH"
    LEVEL_LABEL_DETECTED = "LEVEL_LABEL_DETECTED"
    ELEVATION_SEQUENCE_MATCH = "ELEVATION_SEQUENCE_MATCH"
    VERTICAL_CONTINUITY = "VERTICAL_CONTINUITY"
    EVIDENCE_ALIGNMENT = "EVIDENCE_ALIGNMENT"
    GEOMETRIC_CONSISTENCY = "GEOMETRIC_CONSISTENCY"
    VERTICAL_EXTENT_OVERLAP = "VERTICAL_EXTENT_OVERLAP"
    DISCORDANT_BOUNDARIES = "DISCORDANT_BOUNDARIES"
    UNEXPLAINED_FLOOR_GAP = "UNEXPLAINED_FLOOR_GAP"
    MISSING_EVIDENCE_SUPPORT = "MISSING_EVIDENCE_SUPPORT"
    CONFIDENCE_BELOW_THRESHOLD = "CONFIDENCE_BELOW_THRESHOLD"


class DisagreementType(str, Enum):
    AI_VALIDATION_DISAGREEMENT = "AI_VALIDATION_DISAGREEMENT"
    LOW_AI_CONFIDENCE_GEOMETRICALLY_VALID = "LOW_AI_CONFIDENCE_GEOMETRICALLY_VALID"
    CONSISTENT = "CONSISTENT"
    HUMAN_OVERRIDE_OF_AI_PROPOSAL = "HUMAN_OVERRIDE_OF_AI_PROPOSAL"


class ReproducibilityStatus(str, Enum):
    REPRODUCIBLE = "REPRODUCIBLE"
    PARTIALLY_REPRODUCIBLE = "PARTIALLY_REPRODUCIBLE"
    NOT_REPRODUCIBLE = "NOT_REPRODUCIBLE"


class EvidenceQuality(str, Enum):
    ACCEPTED = "ACCEPTED"
    WARNING = "WARNING"
    BLOCKED = "BLOCKED"


class OperationalRole(str, Enum):
    VIEWER = "VIEWER"
    REVIEWER = "REVIEWER"
    APPROVER = "APPROVER"
    ADMIN = "ADMIN"


class SyncStatus(str, Enum):
    SYNCED = "SYNCED"
    PENDING_SYNC = "PENDING_SYNC"
    CONFLICT = "CONFLICT"
    FAILED_SYNC = "FAILED_SYNC"


